/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AdminEventsRouteRouteImport } from './routes/admin/events/route'
import { Route as EventsEventSlugRouteRouteImport } from './routes/events/$eventSlug/route'
import { Route as EventsPastRouteImport } from './routes/events/past'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as EventsEventSlugIndexRouteImport } from './routes/events/$eventSlug/index'
import { Route as AdminEventsEventSlugEditRouteImport } from './routes/admin/events/$eventSlug/edit'
import { Route as EventsEventSlugSubmissionsIndexRouteImport } from './routes/events/$eventSlug/submissions/index'
import { Route as EventsEventSlugSubmissionsSubmissionIdRouteImport } from './routes/events/$eventSlug/submissions/$submissionId'
import { Route as EventsEventSlugSubmissionsNewRouteImport } from './routes/events/$eventSlug/submissions/new'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRouteRoute = AdminEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EventsEventSlugRouteRoute = EventsEventSlugRouteRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => EventsRouteRoute,
} as any)
const EventsPastRoute = EventsPastRouteImport.update({
  id: '/past',
  path: '/past',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsRouteRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRouteRoute,
} as any)
const EventsEventSlugIndexRoute = EventsEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)
const AdminEventsEventSlugEditRoute =
  AdminEventsEventSlugEditRouteImport.update({
    id: '/$eventSlug/edit',
    path: '/$eventSlug/edit',
    getParentRoute: () => AdminEventsRouteRoute,
  } as any)
const EventsEventSlugSubmissionsIndexRoute =
  EventsEventSlugSubmissionsIndexRouteImport.update({
    id: '/submissions/',
    path: '/submissions/',
    getParentRoute: () => EventsEventSlugRouteRoute,
  } as any)
const EventsEventSlugSubmissionsSubmissionIdRoute =
  EventsEventSlugSubmissionsSubmissionIdRouteImport.update({
    id: '/submissions/$submissionId',
    path: '/submissions/$submissionId',
    getParentRoute: () => EventsEventSlugRouteRoute,
  } as any)
const EventsEventSlugSubmissionsNewRoute =
  EventsEventSlugSubmissionsNewRouteImport.update({
    id: '/submissions/new',
    path: '/submissions/new',
    getParentRoute: () => EventsEventSlugRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRouteRouteWithChildren
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/events/past': typeof EventsPastRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
  '/admin/events/$eventSlug/edit': typeof AdminEventsEventSlugEditRoute
  '/events/$eventSlug/submissions/$submissionId': typeof EventsEventSlugSubmissionsSubmissionIdRoute
  '/events/$eventSlug/submissions/new': typeof EventsEventSlugSubmissionsNewRoute
  '/events/$eventSlug/submissions/': typeof EventsEventSlugSubmissionsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/events/past': typeof EventsPastRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$eventSlug': typeof EventsEventSlugIndexRoute
  '/admin/events/$eventSlug/edit': typeof AdminEventsEventSlugEditRoute
  '/events/$eventSlug/submissions/$submissionId': typeof EventsEventSlugSubmissionsSubmissionIdRoute
  '/events/$eventSlug/submissions/new': typeof EventsEventSlugSubmissionsNewRoute
  '/events/$eventSlug/submissions': typeof EventsEventSlugSubmissionsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRouteRouteWithChildren
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/events/past': typeof EventsPastRoute
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
  '/admin/events/$eventSlug/edit': typeof AdminEventsEventSlugEditRoute
  '/events/$eventSlug/submissions/$submissionId': typeof EventsEventSlugSubmissionsSubmissionIdRoute
  '/events/$eventSlug/submissions/new': typeof EventsEventSlugSubmissionsNewRoute
  '/events/$eventSlug/submissions/': typeof EventsEventSlugSubmissionsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/admin/events'
    | '/events/$eventSlug'
    | '/events/past'
    | '/admin/events/new'
    | '/admin/events/'
    | '/events/$eventSlug/'
    | '/admin/events/$eventSlug/edit'
    | '/events/$eventSlug/submissions/$submissionId'
    | '/events/$eventSlug/submissions/new'
    | '/events/$eventSlug/submissions/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/events/past'
    | '/admin/events/new'
    | '/admin/events'
    | '/events/$eventSlug'
    | '/admin/events/$eventSlug/edit'
    | '/events/$eventSlug/submissions/$submissionId'
    | '/events/$eventSlug/submissions/new'
    | '/events/$eventSlug/submissions'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/admin/events'
    | '/events/$eventSlug'
    | '/events/past'
    | '/admin/events/new'
    | '/admin/events/'
    | '/events/$eventSlug/'
    | '/admin/events/$eventSlug/edit'
    | '/events/$eventSlug/submissions/$submissionId'
    | '/events/$eventSlug/submissions/new'
    | '/events/$eventSlug/submissions/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/events/past': {
      id: '/events/past'
      path: '/past'
      fullPath: '/events/past'
      preLoaderRoute: typeof EventsPastRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminEventsRouteRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRouteRoute
    }
    '/events/$eventSlug/': {
      id: '/events/$eventSlug/'
      path: '/'
      fullPath: '/events/$eventSlug/'
      preLoaderRoute: typeof EventsEventSlugIndexRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
    '/admin/events/$eventSlug/edit': {
      id: '/admin/events/$eventSlug/edit'
      path: '/$eventSlug/edit'
      fullPath: '/admin/events/$eventSlug/edit'
      preLoaderRoute: typeof AdminEventsEventSlugEditRouteImport
      parentRoute: typeof AdminEventsRouteRoute
    }
    '/events/$eventSlug/submissions/': {
      id: '/events/$eventSlug/submissions/'
      path: '/submissions'
      fullPath: '/events/$eventSlug/submissions/'
      preLoaderRoute: typeof EventsEventSlugSubmissionsIndexRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
    '/events/$eventSlug/submissions/$submissionId': {
      id: '/events/$eventSlug/submissions/$submissionId'
      path: '/submissions/$submissionId'
      fullPath: '/events/$eventSlug/submissions/$submissionId'
      preLoaderRoute: typeof EventsEventSlugSubmissionsSubmissionIdRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
    '/events/$eventSlug/submissions/new': {
      id: '/events/$eventSlug/submissions/new'
      path: '/submissions/new'
      fullPath: '/events/$eventSlug/submissions/new'
      preLoaderRoute: typeof EventsEventSlugSubmissionsNewRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
  }
}

interface AdminEventsRouteRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
  AdminEventsEventSlugEditRoute: typeof AdminEventsEventSlugEditRoute
}

const AdminEventsRouteRouteChildren: AdminEventsRouteRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
  AdminEventsEventSlugEditRoute: AdminEventsEventSlugEditRoute,
}

const AdminEventsRouteRouteWithChildren =
  AdminEventsRouteRoute._addFileChildren(AdminEventsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminEventsRouteRoute: typeof AdminEventsRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventsRouteRoute: AdminEventsRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EventsEventSlugRouteRouteChildren {
  EventsEventSlugIndexRoute: typeof EventsEventSlugIndexRoute
  EventsEventSlugSubmissionsSubmissionIdRoute: typeof EventsEventSlugSubmissionsSubmissionIdRoute
  EventsEventSlugSubmissionsNewRoute: typeof EventsEventSlugSubmissionsNewRoute
  EventsEventSlugSubmissionsIndexRoute: typeof EventsEventSlugSubmissionsIndexRoute
}

const EventsEventSlugRouteRouteChildren: EventsEventSlugRouteRouteChildren = {
  EventsEventSlugIndexRoute: EventsEventSlugIndexRoute,
  EventsEventSlugSubmissionsSubmissionIdRoute:
    EventsEventSlugSubmissionsSubmissionIdRoute,
  EventsEventSlugSubmissionsNewRoute: EventsEventSlugSubmissionsNewRoute,
  EventsEventSlugSubmissionsIndexRoute: EventsEventSlugSubmissionsIndexRoute,
}

const EventsEventSlugRouteRouteWithChildren =
  EventsEventSlugRouteRoute._addFileChildren(EventsEventSlugRouteRouteChildren)

interface EventsRouteRouteChildren {
  EventsEventSlugRouteRoute: typeof EventsEventSlugRouteRouteWithChildren
  EventsPastRoute: typeof EventsPastRoute
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventSlugRouteRoute: EventsEventSlugRouteRouteWithChildren,
  EventsPastRoute: EventsPastRoute,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
