/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as EventsRouteRouteImport } from './routes/events/route'
import { Route as AdminEventsRouteRouteImport } from './routes/admin/events/route'
import { Route as EventsEventSlugRouteRouteImport } from './routes/events/$eventSlug/route'
import { Route as AdminEventsIndexRouteImport } from './routes/admin/events/index'
import { Route as AdminEventsNewRouteImport } from './routes/admin/events/new'
import { Route as EventsEventSlugIndexRouteImport } from './routes/events/$eventSlug/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRouteRoute = EventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminEventsRouteRoute = AdminEventsRouteRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EventsEventSlugRouteRoute = EventsEventSlugRouteRouteImport.update({
  id: '/$eventSlug',
  path: '/$eventSlug',
  getParentRoute: () => EventsRouteRoute,
} as any)
const AdminEventsIndexRoute = AdminEventsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminEventsRouteRoute,
} as any)
const AdminEventsNewRoute = AdminEventsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AdminEventsRouteRoute,
} as any)
const EventsEventSlugIndexRoute = EventsEventSlugIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EventsEventSlugRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRouteRouteWithChildren
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events': typeof AdminEventsIndexRoute
  '/events/$eventSlug': typeof EventsEventSlugIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/events': typeof EventsRouteRouteWithChildren
  '/admin/events': typeof AdminEventsRouteRouteWithChildren
  '/events/$eventSlug': typeof EventsEventSlugRouteRouteWithChildren
  '/admin/events/new': typeof AdminEventsNewRoute
  '/admin/events/': typeof AdminEventsIndexRoute
  '/events/$eventSlug/': typeof EventsEventSlugIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/events'
    | '/admin/events'
    | '/events/$eventSlug'
    | '/admin/events/new'
    | '/admin/events/'
    | '/events/$eventSlug/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/events'
    | '/admin/events/new'
    | '/admin/events'
    | '/events/$eventSlug'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/events'
    | '/admin/events'
    | '/events/$eventSlug'
    | '/admin/events/new'
    | '/admin/events/'
    | '/events/$eventSlug/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EventsRouteRoute: typeof EventsRouteRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/events': {
      id: '/admin/events'
      path: '/events'
      fullPath: '/admin/events'
      preLoaderRoute: typeof AdminEventsRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/events/$eventSlug': {
      id: '/events/$eventSlug'
      path: '/$eventSlug'
      fullPath: '/events/$eventSlug'
      preLoaderRoute: typeof EventsEventSlugRouteRouteImport
      parentRoute: typeof EventsRouteRoute
    }
    '/admin/events/': {
      id: '/admin/events/'
      path: '/'
      fullPath: '/admin/events/'
      preLoaderRoute: typeof AdminEventsIndexRouteImport
      parentRoute: typeof AdminEventsRouteRoute
    }
    '/admin/events/new': {
      id: '/admin/events/new'
      path: '/new'
      fullPath: '/admin/events/new'
      preLoaderRoute: typeof AdminEventsNewRouteImport
      parentRoute: typeof AdminEventsRouteRoute
    }
    '/events/$eventSlug/': {
      id: '/events/$eventSlug/'
      path: '/'
      fullPath: '/events/$eventSlug/'
      preLoaderRoute: typeof EventsEventSlugIndexRouteImport
      parentRoute: typeof EventsEventSlugRouteRoute
    }
  }
}

interface AdminEventsRouteRouteChildren {
  AdminEventsNewRoute: typeof AdminEventsNewRoute
  AdminEventsIndexRoute: typeof AdminEventsIndexRoute
}

const AdminEventsRouteRouteChildren: AdminEventsRouteRouteChildren = {
  AdminEventsNewRoute: AdminEventsNewRoute,
  AdminEventsIndexRoute: AdminEventsIndexRoute,
}

const AdminEventsRouteRouteWithChildren =
  AdminEventsRouteRoute._addFileChildren(AdminEventsRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminEventsRouteRoute: typeof AdminEventsRouteRouteWithChildren
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEventsRouteRoute: AdminEventsRouteRouteWithChildren,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EventsEventSlugRouteRouteChildren {
  EventsEventSlugIndexRoute: typeof EventsEventSlugIndexRoute
}

const EventsEventSlugRouteRouteChildren: EventsEventSlugRouteRouteChildren = {
  EventsEventSlugIndexRoute: EventsEventSlugIndexRoute,
}

const EventsEventSlugRouteRouteWithChildren =
  EventsEventSlugRouteRoute._addFileChildren(EventsEventSlugRouteRouteChildren)

interface EventsRouteRouteChildren {
  EventsEventSlugRouteRoute: typeof EventsEventSlugRouteRouteWithChildren
}

const EventsRouteRouteChildren: EventsRouteRouteChildren = {
  EventsEventSlugRouteRoute: EventsEventSlugRouteRouteWithChildren,
}

const EventsRouteRouteWithChildren = EventsRouteRoute._addFileChildren(
  EventsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EventsRouteRoute: EventsRouteRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
